### ISSUE TITLE
Improve caching by allowing `If-Modified-Since`

### ISSUE THREAD

**Issue by warlof** [cvweiss/sde2json#2]
Hello,

I am using the hosted version on sde.zzeve.com in a Discourse Javascript plugin.

In order to reduce loading time and bandwidth consumption, I would send my requests using `If-Modified-Since` header, but doing so is returning me an HTTP OPTIONS due to CORS issue.

Could you add the header into allowed header?

**Comment by cvweiss** [comment]
I just checked the configuration and that header is already allowed:

> Access-Control-Allow-Headers: DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range

I verified this with Chrome as well, which is sending the ```If-Modified-Since``` header and receiving a 304 back. Are you getting some other unexpected behavior?

**Comment by warlof** [comment]
Hi @cvweiss ,

Apologies for the delayed reply.
I've tried to try again to send a request including `If-Modified-Since` header but still get the 405 due to CORS issue.

Here is the part of the script I'm using :
```
$.ajax({
	dataType: 'json',
	headers: {
		'If-Modified-Since': meta.lastModified
	},
	method: 'GET',
	url: EVE_ONLINE_SDE_CDN + '/' + tableName + '.json'
}).done(function(data, textStatus, jqXHR) {
	console.debug(jqXHR.getAllResponseHeaders());
	
	if (meta.lastModified !== jqXHR.getResponseHeader('Last-Modified')) {
		console.warn('refreshing data for ' + tableName);
		
		// emptying tableName in order to reload updated information
		db[tableName].clear();
		
		// seeding tableName with updated information
		if (data.length > 0) db[tableName].bulkAdd(data);
		
		// update metadata related to tableName
		db.meta.update(tableName, {
			etag: jqXHR.getResponseHeader('ETag'),
			lastModified: jqXHR.getResponseHeader('Last-Modified')
		}).catch(function (err) {
			console.error(err);
		});
	}
}).fail(function(jqXHR, textStatus, errorThrown) {
	console.error(textStatus);
	console.error(errorThrown);
});
```
`tableName` is either `invTypes` or `dgmAttributeTypes`.

I'm getting this from Firefox console :

```
"Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://sde.zzeve.com/invTypers.json Reason: CORS header 'Access-Control-Allow-Origin' missing"
```

If I'm removing the `If-Modified-Since` request, it's working without troubles.
